import { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { StickyNote, Plus, Trash2, X, Pin, Clock, Search, Sparkles, Download } from 'lucide-react';
import { jsPDF } from 'jspdf';
import './NotesPanel.css';

const STORAGE_KEY = 'nebula-user-notes';

function loadNotes() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch { return []; }
}

function saveNotes(notes) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(notes));
}

export default function NotesPanel({ isOpen, onClose }) {
  const [notes, setNotes] = useState(loadNotes);
  const [activeNote, setActiveNote] = useState(null);
  const [search, setSearch] = useState('');
  const textareaRef = useRef(null);

  useEffect(() => { saveNotes(notes); }, [notes]);

  useEffect(() => {
    if (activeNote !== null && textareaRef.current) {
      textareaRef.current.focus();
    }
  }, [activeNote]);

  const addNote = () => {
    const newNote = {
      id: Date.now(),
      title: '',
      content: '',
      color: ['blue', 'purple', 'cyan', 'green', 'orange'][Math.floor(Math.random() * 5)],
      pinned: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    setNotes([newNote, ...notes]);
    setActiveNote(newNote.id);
  };

  const updateNote = (id, field, value) => {
    setNotes(notes.map(n =>
      n.id === id ? { ...n, [field]: value, updatedAt: new Date().toISOString() } : n
    ));
  };

  const deleteNote = (id) => {
    setNotes(notes.filter(n => n.id !== id));
    if (activeNote === id) setActiveNote(null);
  };

  const togglePin = (id) => {
    setNotes(notes.map(n =>
      n.id === id ? { ...n, pinned: !n.pinned } : n
    ));
  };

  const downloadNote = (note) => {
    const title = note.title || 'Untitled Note';
    const content = note.content || '';
    const fileName = `${title.replace(/[^a-z0-9]/gi, '_')}.pdf`;

    const generatePDF = (logoDataUrl) => {
      const doc = new jsPDF('p', 'mm', 'a4');
      const pageW = doc.internal.pageSize.getWidth();
      const pageH = doc.internal.pageSize.getHeight();

      const addWatermark = () => {
        if (logoDataUrl) {
          const wSize = 80;
          doc.saveGraphicsState();
          doc.setGState(new doc.GState({ opacity: 0.06 }));
          doc.addImage(logoDataUrl, 'PNG', (pageW - wSize) / 2, (pageH - wSize) / 2, wSize, wSize);
          doc.restoreGraphicsState();
        }
      };

      // Page 1 watermark
      addWatermark();

      // Header bar
      doc.setFillColor(59, 109, 224);
      doc.rect(0, 0, pageW, 28, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.text(title, 14, 17);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.text('Nebula KnowLab™', pageW - 14, 10, { align: 'right' });
      doc.text(`Exported: ${new Date().toLocaleDateString()}`, pageW - 14, 16, { align: 'right' });

      // Content
      doc.setTextColor(30, 30, 30);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      const lines = doc.splitTextToSize(content, pageW - 28);
      let y = 38;
      const lineH = 6;

      for (let i = 0; i < lines.length; i++) {
        if (y + lineH > pageH - 20) {
          doc.addPage();
          addWatermark();
          y = 20;
        }
        doc.text(lines[i], 14, y);
        y += lineH;
      }

      // Footer on last page
      doc.setFontSize(7);
      doc.setTextColor(150, 150, 150);
      doc.text('Generated by Nebula KnowLab • Industrial Robotics Learning Platform', pageW / 2, pageH - 8, { align: 'center' });

      doc.save(fileName);
    };

    // Load logo, then generate PDF
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = img.naturalWidth;
      canvas.height = img.naturalHeight;
      const ctx = canvas.getContext('2d');
      ctx.drawImage(img, 0, 0);
      generatePDF(canvas.toDataURL('image/png'));
    };
    img.onerror = () => generatePDF(null);
    img.src = './nebula-logo.png';
  };

  const filtered = notes
    .filter(n => {
      if (!search) return true;
      const s = search.toLowerCase();
      return n.title.toLowerCase().includes(s) || n.content.toLowerCase().includes(s);
    })
    .sort((a, b) => {
      if (a.pinned && !b.pinned) return -1;
      if (!a.pinned && b.pinned) return 1;
      return new Date(b.updatedAt) - new Date(a.updatedAt);
    });

  const active = notes.find(n => n.id === activeNote);

  const timeAgo = (iso) => {
    const diff = Date.now() - new Date(iso).getTime();
    const mins = Math.floor(diff / 60000);
    if (mins < 1) return 'Just now';
    if (mins < 60) return `${mins}m ago`;
    const hrs = Math.floor(mins / 60);
    if (hrs < 24) return `${hrs}h ago`;
    return `${Math.floor(hrs / 24)}d ago`;
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          className="notes-panel"
          initial={{ x: -340, opacity: 0 }}
          animate={{ x: 0, opacity: 1 }}
          exit={{ x: -340, opacity: 0 }}
          transition={{ type: 'spring', stiffness: 300, damping: 30 }}
        >
          {/* Header */}
          <div className="notes-header">
            <div className="notes-header-left">
              <StickyNote size={18} className="notes-icon" />
              <h3>My Notes</h3>
              <span className="notes-count">{notes.length}</span>
            </div>
            <div className="notes-header-right">
              <button className="notes-btn-icon" onClick={addNote} title="New Note">
                <Plus size={16} />
              </button>
              <button className="notes-btn-icon" onClick={onClose} title="Close">
                <X size={16} />
              </button>
            </div>
          </div>

          {/* Search */}
          <div className="notes-search">
            <Search size={14} />
            <input
              type="text"
              placeholder="Search notes..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
          </div>

          {/* Editor / List split */}
          {active ? (
            <div className="notes-editor">
              <div className="notes-editor-header">
                <button className="notes-btn-back" onClick={() => setActiveNote(null)}>
                  ← Back
                </button>
                <div className="notes-editor-actions">
                  <button
                    className="notes-btn-icon"
                    onClick={() => downloadNote(active)}
                    title="Download note"
                  >
                    <Download size={14} />
                  </button>
                  <button
                    className={`notes-btn-icon ${active.pinned ? 'pinned' : ''}`}
                    onClick={() => togglePin(active.id)}
                  >
                    <Pin size={14} />
                  </button>
                  <button className="notes-btn-icon danger" onClick={() => deleteNote(active.id)}>
                    <Trash2 size={14} />
                  </button>
                </div>
              </div>
              <input
                className="notes-title-input"
                type="text"
                placeholder="Note title..."
                value={active.title}
                onChange={(e) => updateNote(active.id, 'title', e.target.value)}
              />
              <div className={`notes-color-bar color-${active.color}`} />
              <textarea
                ref={textareaRef}
                className="notes-content-input"
                placeholder="Start writing your notes here...&#10;&#10;💡 Tip: Use notes to capture key concepts, questions, or insights as you learn!"
                value={active.content}
                onChange={(e) => updateNote(active.id, 'content', e.target.value)}
              />
              {/* Nebula KnowLab watermark */}
              <div className="notes-watermark">
                <img src="./nebula-logo.png" alt="" className="notes-watermark-img" />
                <span className="notes-watermark-text">Nebula KnowLab™</span>
              </div>
              <div className="notes-editor-meta">
                <Clock size={12} />
                <span>{timeAgo(active.updatedAt)}</span>
                <span>·</span>
                <span>{active.content.split(/\s+/).filter(Boolean).length} words</span>
              </div>
            </div>
          ) : (
            <div className="notes-list">
              {filtered.length === 0 ? (
                <div className="notes-empty">
                  <Sparkles size={32} className="notes-empty-icon" />
                  <p>No notes yet</p>
                  <span>Click <strong>+</strong> to create your first note</span>
                  <button className="notes-add-first" onClick={addNote}>
                    <Plus size={14} /> New Note
                  </button>
                </div>
              ) : (
                filtered.map((note, i) => (
                  <motion.div
                    key={note.id}
                    className={`notes-card color-${note.color}`}
                    initial={{ opacity: 0, y: 8 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: i * 0.03 }}
                    onClick={() => setActiveNote(note.id)}
                  >
                    <div className="notes-card-top">
                      <h4>{note.title || 'Untitled Note'}</h4>
                      {note.pinned && <Pin size={12} className="notes-pin" />}
                    </div>
                    <p className="notes-card-preview">
                      {note.content ? note.content.substring(0, 80) + (note.content.length > 80 ? '...' : '') : 'Empty note'}
                    </p>
                    <span className="notes-card-time">{timeAgo(note.updatedAt)}</span>
                  </motion.div>
                ))
              )}
            </div>
          )}
        </motion.div>
      )}
    </AnimatePresence>
  );
}
